const Database = {
  products: [
    {
      id: 1,
      title: "Essence Mascara Lash Princess",
      description:
        "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects.",
      category: "beauty",
      brand: "Essence",
      model: "",
      price: 9.99,
      discount: 10.48,
      rating: 2.56,
      tags: ["beauty", "mascara"],
      images: [
        "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp",
      ],
      thumbnail:
        "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp",
      withGifts: true,
      isNew: true,
    },
    {
      id: 2,
      title: "Eyeshadow Palette with Mirror",
      description:
        "The Eyeshadow Palette with Mirror offers a versatile range of shades.",
      category: "beauty",
      brand: "Glamour Beauty",
      model: "",
      price: 19.99,
      discount: 18.19,
      rating: 2.86,
      tags: ["beauty", "eyeshadow"],
      images: [
        "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp",
      ],
      thumbnail:
        "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp",
      withGifts: true,
      isNew: false,
    },
    {
      id: 3,
      title: "Powder Canister",
      description: "Finely milled setting powder for smooth matte finish.",
      category: "beauty",
      brand: "Velvet Touch",
      model: "",
      price: 14.99,
      discount: 9.84,
      rating: 4.64,
      tags: ["beauty", "face powder"],
      images: [
        "https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp",
      ],
      thumbnail:
        "https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp",
      withGifts: false,
      isNew: true,
    },
    {
      id: 4,
      title: "Red Lipstick",
      description: "Bold and vibrant lipstick with long-lasting finish.",
      category: "beauty",
      brand: "Chic Cosmetics",
      model: "",
      price: 12.99,
      discount: 0,
      rating: 4.36,
      tags: ["beauty", "lipstick"],
      images: [
        "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp",
      ],
      thumbnail:
        "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp",
      withGifts: false,
      isNew: true,
    },
    {
      id: 5,
      title: "Red Nail Polish",
      description: "Glossy red nail polish with quick-dry formula.",
      category: "beauty",
      brand: "Nail Couture",
      model: "",
      price: 8.99,
      discount: 11.44,
      rating: 4.32,
      tags: ["beauty", "nail polish"],
      images: [
        "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp",
      ],
      thumbnail:
        "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp",
      withGifts: false,
      isNew: false,
    },
    {
      id: 6,
      title: "Calvin Klein CK One",
      description: "Classic unisex fragrance with fresh scent.",
      category: "fragrances",
      brand: "Calvin Klein",
      model: "CK One",
      price: 49.99,
      discount: 1.89,
      rating: 4.37,
      tags: ["fragrances", "perfumes"],
      images: [
        "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp",
        "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp",
        "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp",
      ],
      thumbnail:
        "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp",
      withGifts: false,
      isNew: false,
    },
    {
      id: 7,
      title: "Chanel Coco Noir",
      description: "Elegant fragrance with rose and sandalwood notes.",
      category: "fragrances",
      brand: "Chanel",
      model: "Coco Noir",
      price: 129.99,
      discount: 16.51,
      rating: 4.26,
      tags: ["fragrances", "perfumes"],
      images: [
        "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp",
      ],
      thumbnail:
        "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp",
      withGifts: false,
      isNew: false,
    },
    {
      id: 8,
      title: "Dior J'adore",
      description: "Luxurious floral fragrance with jasmine notes.",
      category: "fragrances",
      brand: "Dior",
      model: "J'adore",
      price: 89.99,
      discount: 14.72,
      rating: 3.8,
      tags: ["fragrances", "perfumes"],
      images: [
        "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/1.webp",
      ],
      thumbnail:
        "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp",
      withGifts: false,
      isNew: false,
    },
    {
      id: 9,
      title: "Dolce Shine",
      description: "Fruity fragrance with mango and jasmine.",
      category: "fragrances",
      brand: "Dolce & Gabbana",
      model: "Dolce Shine",
      price: 69.99,
      discount: 0.62,
      rating: 3.96,
      tags: ["fragrances", "perfumes"],
      images: [
        "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp",
      ],
      thumbnail:
        "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp",
      withGifts: false,
      isNew: false,
    },
    {
      id: 10,
      title: "Gucci Bloom",
      description: "Floral fragrance with tuberose and jasmine.",
      category: "fragrances",
      brand: "Gucci",
      model: "Bloom",
      price: 79.99,
      discount: 14.39,
      rating: 2.74,
      tags: ["fragrances", "perfumes"],
      images: [
        "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp",
      ],
      thumbnail:
        "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp",
      withGifts: false,
      isNew: false,
    },
  ],
};

export default Database;
